// ── src/generator.cpp ─────────────────────────────────────────────────────
// SPDX-License-Identifier: Apache-2.0
// ──────────────────────────────────────────────────────────────────────────

#include <zconfig/generator.hpp>
#include <zconfig/log.hpp>
#include <fstream>
#include <format>

namespace zconfig {

Result<void> Generator::run(const Registry& reg) {
    for (const auto& gen : reg.get_generators()) {
        ZLOG_INFO("Generating output: {} (backend: {})", gen->output_path, (int)gen->backend);
        Result<void> res;
        switch (gen->backend) {
            case GeneratorBackend::Header:   res = emit_header(reg, gen->output_path); break;
            case GeneratorBackend::Makefile: res = emit_makefile(reg, gen->output_path); break;
            case GeneratorBackend::JSON:     res = emit_json(reg, gen->output_path); break;
        }
        if (!res) return res;
    }
    return {};
}

Result<void> Generator::emit_header(const Registry& reg, const std::string& path) {
    std::ofstream f(path);
    if (!f.is_open()) return std::unexpected(Diagnostic::build(ErrorCode::InternalError, "Could not open header for writing: " + path));

    f << "// Generated by Zconfig\n#pragma once\n\n";
    auto emit_macro = [&](const std::string& name, bool visible, Type type, const Value& computed_value) {
        if (!visible) return;
        
        std::string macro_name = name;
        std::replace(macro_name.begin(), macro_name.end(), '.', '_');

        if (type == Type::Bool) {
            if (std::get<bool>(computed_value)) f << "#define CONFIG_" << macro_name << " 1\n";
        } else if (type == Type::Int) {
            f << "#define CONFIG_" << macro_name << " " << std::get<int64_t>(computed_value) << "\n";
        } else if (type == Type::String || type == Type::Enum) {
            f << "#define CONFIG_" << macro_name << " \"" << std::get<std::string>(computed_value) << "\"\n";
        } else if (type == Type::Set) {
            const auto& vec = std::get<std::vector<std::string>>(computed_value);
            f << "#define CONFIG_" << macro_name << " \"";
            for (size_t i = 0; i < vec.size(); ++i) {
                f << vec[i] << (i == vec.size() - 1 ? "" : " ");
            }
            f << "\"\n";
            for (const auto& item : vec) {
                std::string item_name = item;
                std::replace(item_name.begin(), item_name.end(), '.', '_');
                f << "#define CONFIG_" << macro_name << "_" << item_name << " 1\n";
            }
        }
    };

    for (const auto& [name, sym] : reg.get_symbols()) {
        emit_macro(name, sym->is_effectively_visible(), sym->type, sym->computed_value);
    }
    for (const auto& [name, sym] : reg.get_computed()) {
        emit_macro(name, sym->is_effectively_visible(), sym->type, sym->value);
    }
    return {};
}

Result<void> Generator::emit_makefile(const Registry& reg, const std::string& path) {
    std::ofstream f(path);
    if (!f.is_open()) return std::unexpected(Diagnostic::build(ErrorCode::InternalError, "Could not open makefile for writing: " + path));

    f << "# Generated by Zconfig\n\n";
    auto emit_mk = [&](const std::string& name, bool visible, Type type, const Value& computed_value) {
        if (!visible) return;

        std::string mk_name = name;
        std::replace(mk_name.begin(), mk_name.end(), '.', '_');

        if (type == Type::Bool) {
            f << "CONFIG_" << mk_name << " := " << (std::get<bool>(computed_value) ? "y" : "n") << "\n";
        } else if (type == Type::Int) {
            f << "CONFIG_" << mk_name << " := " << std::get<int64_t>(computed_value) << "\n";
        } else if (type == Type::String || type == Type::Enum) {
            f << "CONFIG_" << mk_name << " := " << std::get<std::string>(computed_value) << "\n";
        } else if (type == Type::Set) {
            f << "CONFIG_" << mk_name << " :=";
            for (const auto& s : std::get<std::vector<std::string>>(computed_value)) {
                f << " " << s;
            }
            f << "\n";
        }
    };

    for (const auto& [name, sym] : reg.get_symbols()) {
        emit_mk(name, sym->is_effectively_visible(), sym->type, sym->computed_value);
    }
    for (const auto& [name, sym] : reg.get_computed()) {
        emit_mk(name, sym->is_effectively_visible(), sym->type, sym->value);
    }
    return {};
}

Result<void> Generator::emit_json(const Registry& reg, const std::string& path) {
    std::ofstream f(path);
    if (!f.is_open()) return std::unexpected(Diagnostic::build(ErrorCode::InternalError, "Could not open JSON for writing: " + path));

    f << "{\n";
    bool first = true;
    auto emit_j = [&](const std::string& name, bool visible, Type type, const Value& computed_value) {
        if (!visible) return;
        if (!first) f << ",\n";
        first = false;

        f << "  \"" << name << "\": ";
        if (type == Type::Bool) {
            f << (std::get<bool>(computed_value) ? "true" : "false");
        } else if (type == Type::Int) {
            f << std::get<int64_t>(computed_value);
        } else if (type == Type::String || type == Type::Enum) {
            f << "\"" << std::get<std::string>(computed_value) << "\"";
        } else if (type == Type::Set) {
            f << "[";
            const auto& vec = std::get<std::vector<std::string>>(computed_value);
            for (size_t i = 0; i < vec.size(); ++i) {
                f << "\"" << vec[i] << "\"" << (i == vec.size() - 1 ? "" : ", ");
            }
            f << "]";
        }
    };

    for (const auto& [name, sym] : reg.get_symbols()) {
        emit_j(name, sym->is_effectively_visible(), sym->type, sym->computed_value);
    }
    for (const auto& [name, sym] : reg.get_computed()) {
        emit_j(name, sym->is_effectively_visible(), sym->type, sym->value);
    }
    f << "\n}\n";
    return {};
}

}
